// Autogenerated by ioctlgen.py

#include "nvwrapper.h"

const char *ioctl2str(LinuxNvhostCtrlGpuIoctl value) {
	switch(value) {
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_GET_TPC_EXCEPTION_EN_STATUS:
		return "NVGPU_GPU_IOCTL_GET_TPC_EXCEPTION_EN_STATUS";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_VSMS_MAPPING:
		return "NVGPU_GPU_IOCTL_VSMS_MAPPING";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_INVAL_ICACHE:
		return "NVGPU_GPU_IOCTL_INVAL_ICACHE";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_GET_TPC_MASKS:
		return "NVGPU_GPU_IOCTL_GET_TPC_MASKS";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_ZBC_SET_TABLE:
		return "NVGPU_GPU_IOCTL_ZBC_SET_TABLE";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_ZBC_QUERY_TABLE:
		return "NVGPU_GPU_IOCTL_ZBC_QUERY_TABLE";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_MARK_COMPRESSIBLE_WRITE:
		return "NVGPU_GPU_IOCTL_MARK_COMPRESSIBLE_WRITE";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_OPEN_TSG:
		return "NVGPU_GPU_IOCTL_OPEN_TSG";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_OPEN_CHANNEL:
		return "NVGPU_GPU_IOCTL_OPEN_CHANNEL";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_SET_SM_DEBUG_MODE:
		return "NVGPU_GPU_IOCTL_SET_SM_DEBUG_MODE";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_FLUSH_L2:
		return "NVGPU_GPU_IOCTL_FLUSH_L2";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_ZCULL_GET_INFO:
		return "NVGPU_GPU_IOCTL_ZCULL_GET_INFO";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_GET_CHARACTERISTICS:
		return "NVGPU_GPU_IOCTL_GET_CHARACTERISTICS";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_ALLOC_AS:
		return "NVGPU_GPU_IOCTL_ALLOC_AS";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_SET_MMUDEBUG_MODE:
		return "NVGPU_GPU_IOCTL_SET_MMUDEBUG_MODE";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_ZCULL_GET_CTX_SIZE:
		return "NVGPU_GPU_IOCTL_ZCULL_GET_CTX_SIZE";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_NUM_VSMS:
		return "NVGPU_GPU_IOCTL_NUM_VSMS";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_PREPARE_COMPRESSIBLE_READ:
		return "NVGPU_GPU_IOCTL_PREPARE_COMPRESSIBLE_READ";
	case LinuxNvhostCtrlGpuIoctl::NVGPU_GPU_IOCTL_WAIT_FOR_PAUSE:
		return "NVGPU_GPU_IOCTL_WAIT_FOR_PAUSE";
	default:
		return "UNKNOWN";
	}
}
